class DummyData {
      static List<Map<String, dynamic>> get patients => [
        {
          'id': 'P001',
          'name': 'Amina Bello',
          'age': 28,
          'phone': '+234 801 234 5678',
          'lmp': '2026-02-10',
          'edd': '2026-11-17',
          'gestationalAge': '20 weeks',
          'gravida': 2,
          'para': 1,
          'risk': 'High',
          'riskColor': 'red',
          'bloodType': 'O+',
          'weight': '68 kg',
          'height': '162 cm',
          'bmi': '25.9',
          'bloodPressure': '140/90 mmHg',
          'heartRate': '88 bpm',
          'temperature': '37.2°C',
          'bloodSugar': '5.5 mmol/L',
          'hemoglobin': '9.8 g/dL',
          'previousComplications': 1.0,
          'preexistingDiabetes': 0.0,
          'gestationalDiabetes': 0.0,
          'mentalHealth': 0.0,
          'address': '14 Lafia Street, Yola, Adamawa State',
          'synced': true,
          'lastVisit': '2026-06-28',
          'nextVisit': '2026-07-12',
          'screeningCount': 3,
        },
        {
          'id': 'P002',
          'name': 'Fatima Musa',
          'age': 24,
          'phone': '+234 802 345 6789',
          'lmp': '2026-03-05',
          'edd': '2026-12-10',
          'gestationalAge': '17 weeks',
          'gravida': 1,
          'para': 0,
          'risk': 'Low',
          'riskColor': 'green',
          'bloodType': 'A+',
          'weight': '62 kg',
          'height': '158 cm',
          'bmi': '24.8',
          'bloodPressure': '110/70 mmHg',
          'heartRate': '76 bpm',
          'temperature': '36.8°C',
          'hemoglobin': '11.5 g/dL',
          'address': '7 Unity Road, Jimeta, Adamawa State',
          'synced': true,
          'lastVisit': '2026-06-25',
          'nextVisit': '2026-07-09',
          'screeningCount': 1,
        },
        {
          'id': 'P003',
          'name': 'Hauwa Ibrahim',
          'age': 32,
          'phone': '+234 803 456 7890',
          'lmp': '2026-01-20',
          'edd': '2026-10-27',
          'gestationalAge': '23 weeks',
          'gravida': 3,
          'para': 2,
          'risk': 'Medium',
          'riskColor': 'orange',
          'bloodType': 'B+',
          'weight': '75 kg',
          'height': '165 cm',
          'bmi': '27.5',
          'bloodPressure': '125/80 mmHg',
          'heartRate': '80 bpm',
          'temperature': '37.0°C',
          'hemoglobin': '10.2 g/dL',
          'address': '22 Hospital Road, Mubi, Adamawa State',
          'synced': false,
          'lastVisit': '2026-06-20',
          'nextVisit': '2026-07-04',
          'screeningCount': 4,
        },
        {
          'id': 'P004',
          'name': 'Zainab Adamu',
          'age': 26,
          'phone': '+234 804 567 8901',
          'lmp': '2026-04-01',
          'edd': '2027-01-06',
          'gestationalAge': '13 weeks',
          'gravida': 1,
          'para': 0,
          'risk': 'Low',
          'riskColor': 'green',
          'bloodType': 'AB+',
          'weight': '58 kg',
          'height': '155 cm',
          'bmi': '24.1',
          'bloodPressure': '108/68 mmHg',
          'heartRate': '72 bpm',
          'temperature': '36.6°C',
          'hemoglobin': '12.1 g/dL',
          'address': '5 New Market Street, Numan, Adamawa State',
          'synced': true,
          'lastVisit': '2026-06-15',
          'nextVisit': '2026-07-20',
          'screeningCount': 0,
        },
        {
          'id': 'P005',
          'name': 'Maryam Yusuf',
          'age': 30,
          'phone': '+234 805 678 9012',
          'lmp': '2025-12-15',
          'edd': '2026-09-22',
          'gestationalAge': '28 weeks',
          'gravida': 2,
          'para': 1,
          'risk': 'High',
          'riskColor': 'red',
          'bloodType': 'O-',
          'weight': '82 kg',
          'height': '160 cm',
          'bmi': '32.0',
          'bloodPressure': '145/95 mmHg',
          'heartRate': '92 bpm',
          'temperature': '37.4°C',
          'hemoglobin': '8.9 g/dL',
          'address': '30 Fombina Way, Yola, Adamawa State',
          'synced': true,
          'lastVisit': '2026-07-01',
          'nextVisit': '2026-07-08',
          'screeningCount': 6,
        },
      ];

  static List<Map<String, dynamic>> get screenings => [
        {
          'id': 'SCR001',
          'patientId': 'P001',
          'patientName': 'Amina Bello',
          'date': '2026-06-28',
          'type': 'Routine ANC',
          'riskLevel': 'High',
          'gestationalAge': '19 weeks',
          'bloodPressure': '140/90',
          'weight': '68 kg',
          'status': 'Completed',
          'recommendation': 'Immediate referral to secondary care. Monitor BP every 2 days.',
          'aiScore': 87,
          'findings': [
            'Elevated blood pressure (pre-eclampsia risk)',
            'Low hemoglobin (anemia)',
            'Excessive weight gain',
          ],
        },
        {
          'id': 'SCR002',
          'patientId': 'P001',
          'patientName': 'Amina Bello',
          'date': '2026-06-14',
          'type': 'Follow-up',
          'riskLevel': 'Medium',
          'gestationalAge': '17 weeks',
          'bloodPressure': '132/85',
          'weight': '66 kg',
          'status': 'Completed',
          'recommendation': 'Continue iron supplementation. Return in 2 weeks.',
          'aiScore': 62,
          'findings': [
            'Slightly elevated BP',
            'Low hemoglobin improving',
          ],
        },
        {
          'id': 'SCR003',
          'patientId': 'P005',
          'patientName': 'Maryam Yusuf',
          'date': '2026-07-01',
          'type': 'Emergency',
          'riskLevel': 'High',
          'gestationalAge': '28 weeks',
          'bloodPressure': '145/95',
          'weight': '82 kg',
          'status': 'Completed',
          'recommendation': 'Immediate hospital admission. High eclampsia risk.',
          'aiScore': 92,
          'findings': [
            'Severe hypertension',
            'Severe anemia',
            'Obesity',
            'Previous complicated pregnancy',
          ],
        },
        {
          'id': 'SCR004',
          'patientId': 'P002',
          'patientName': 'Fatima Musa',
          'date': '2026-06-25',
          'type': 'Routine ANC',
          'riskLevel': 'Low',
          'gestationalAge': '16 weeks',
          'bloodPressure': '110/70',
          'weight': '62 kg',
          'status': 'Completed',
          'recommendation': 'Continue routine care. Next visit in 2 weeks.',
          'aiScore': 15,
          'findings': [
            'All vitals normal',
            'Good fetal development',
          ],
        },
      ];

  static List<Map<String, dynamic>> get reports => [
        {
          'id': 'RPT001',
          'patientId': 'P001',
          'patientName': 'Amina Bello',
          'date': '2026-06-28',
          'type': 'Screening Report',
          'screeningId': 'SCR001',
          'riskLevel': 'High',
          'generatedBy': 'MaternalCare AI',
        },
        {
          'id': 'RPT002',
          'patientId': 'P005',
          'patientName': 'Maryam Yusuf',
          'date': '2026-07-01',
          'type': 'Emergency Report',
          'screeningId': 'SCR003',
          'riskLevel': 'High',
          'generatedBy': 'MaternalCare AI',
        },
        {
          'id': 'RPT003',
          'patientId': 'P002',
          'patientName': 'Fatima Musa',
          'date': '2026-06-25',
          'type': 'ANC Report',
          'screeningId': 'SCR004',
          'riskLevel': 'Low',
          'generatedBy': 'MaternalCare AI',
        },
        {
          'id': 'RPT004',
          'patientId': 'P003',
          'patientName': 'Hauwa Ibrahim',
          'date': '2026-06-20',
          'type': 'Follow-up Report',
          'screeningId': 'SCR002',
          'riskLevel': 'Medium',
          'generatedBy': 'MaternalCare AI',
        },
      ];

  static Map<String, dynamic> get currentUser => {
        'name': 'ASHA WORKER',
        'role': 'Community Health Worker',
        'facility': 'Yola Primary Health Center',
        'phone': '+234 806 789 0123',
        'email': 'ngozi.okonkwo@phc.ng',
        'staffId': 'CHW-ADM-2024-047',
        'state': 'Adamawa State',
        'lga': 'Yola North',
        'totalPatients': 5,
        'totalScreenings': 14,
        'highRiskCount': 2,
        'synced': 12,
        'unsynced': 2,
      };

  static Map<String, dynamic> get dashboardStats => {
        'totalPatients': 5,
        'screeningsToday': 2,
        'highRisk': 2,
        'pendingSync': 2,
        'thisWeekScreenings': 7,
        'thisMonthScreenings': 14,
      };

  static List<Map<String, dynamic>> get patientHistory => [
        {
          'date': '2026-06-28',
          'type': 'Screening',
          'title': 'Routine ANC Screening',
          'description': 'High risk detected. Referred to secondary care.',
          'icon': 'medical_services',
          'riskLevel': 'High',
        },
        {
          'date': '2026-06-14',
          'type': 'Screening',
          'title': 'Follow-up Screening',
          'description': 'Medium risk. Continue iron supplementation.',
          'icon': 'medical_services',
          'riskLevel': 'Medium',
        },
        {
          'date': '2026-05-31',
          'type': 'Visit',
          'title': 'ANC Visit - 1st Trimester',
          'description': 'Initial registration and baseline vitals recorded.',
          'icon': 'local_hospital',
          'riskLevel': 'Low',
        },
        {
          'date': '2026-05-10',
          'type': 'Registration',
          'title': 'Patient Registered',
          'description': 'New patient added to MaternalCare system.',
          'icon': 'person_add',
          'riskLevel': null,
        },
      ];
}
